require iRODS 4.1.8 for v1.3

diff --git a/packaging/irods_resource_plugin_s3.list.template b/packaging/irods_resource_plugin_s3.list.template
--- a/packaging/irods_resource_plugin_s3.list.template
+++ b/packaging/irods_resource_plugin_s3.list.template
@@ -1,5 +1,5 @@
 %product Amazon S3 Resource Plugin for iRODS
-%copyright 2014 by Renaissance Computing Institute, All Rights Reserved
+%copyright 2016 by Renaissance Computing Institute, All Rights Reserved
 %vendor Renaissance Computing Institute <info@irods-consortium.org>
 %license LICENSE
 %readme README
@@ -16,6 +16,21 @@
 %requires libxml2
 %requires curl
 %endif
+
+
+# =-=-=-=-=-=-=-
+# preinstall
+# =-=-=-=-=-=-=-
+%preinstall << END_PREINSTALL
+REQUIRED_VERSION="4.1.8"
+DETECTED_VERSION=`python -c 'import json; print json.loads(open("/var/lib/irods/VERSION.json").read())["irods_version"]'`
+if [ "$$DETECTED_VERSION" != "$$REQUIRED_VERSION" ] ; then
+    echo "Local iRODS is $$DETECTED_VERSION"
+    echo "This plugin requires iRODS $$REQUIRED_VERSION"
+    exit 1
+fi
+END_PREINSTALL
+
 
 # =-=-=-=-=-=-=-
 # variables for configuring the install
